# Generated by Django 4.2.23 on 2025-12-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="ai_verdict",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="compare_job_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="deep_verdict",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="dtw_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="final_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="ref_job_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="stgcn_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="user_job_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="window_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="windows",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
