# Generated by Django 4.2.23 on 2025-12-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_testresult_ai_verdict_testresult_compare_job_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="strengths",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="weaknesses",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
